# Generated by Django 2.2.6 on 2020-02-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominaenc',
            name='plantilla',
            field=models.IntegerField(default=0),
        ),
    ]
