# Generated by Django 2.2.6 on 2020-02-21 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nomina',
        ),
    ]
