# Generated by Django 2.2.6 on 2020-02-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominadet',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='nominadet',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='nominadet',
            name='fm',
        ),
        migrations.RemoveField(
            model_name='nominadet',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='nominadet',
            name='um',
        ),
        migrations.RemoveField(
            model_name='nominaenc',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='nominaenc',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='nominaenc',
            name='fm',
        ),
        migrations.RemoveField(
            model_name='nominaenc',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='nominaenc',
            name='um',
        ),
    ]
