# Generated by Django 2.2.6 on 2020-02-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_nominaenc_plantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptonomina',
            name='tipo_concepto',
            field=models.CharField(blank=True, choices=[('PERCEPCION', 'PERCEPCION'), ('DEDUCCION', 'DEDUCCION')], max_length=30, null=True),
        ),
    ]
