# Generated by Django 2.2.6 on 2020-02-21 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_auto_20200221_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominadet',
            name='nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nomina.NominaEnc'),
        ),
    ]
