# Generated by Django 2.2.6 on 2020-02-18 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_auto_20200217_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominaenc',
            name='plantilla',
        ),
    ]
