# Generated by Django 2.2.6 on 2020-02-21 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomina', '0004_auto_20200221_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominadet',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nominadet',
            name='fc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominadet',
            name='fm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nominadet',
            name='uc',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominadet',
            name='um',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
