# Generated by Django 2.2.6 on 2020-02-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_remove_nominaenc_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominaenc',
            name='plantilla',
            field=models.IntegerField(default=0),
        ),
    ]
