# Generated by Django 2.2.6 on 2020-03-02 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion_cuenta_gasto', models.CharField(help_text='Descripción Categoria', max_length=100, unique=True)),
                ('id_cuenta_gasto', models.CharField(help_text='Clave o ID  ', max_length=6, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cuentas Gastos',
            },
        ),
        migrations.CreateModel(
            name='GastosSubCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion_subcuenta_gasto', models.CharField(help_text='Descripción SubCuenta', max_length=100)),
                ('id_subcuenta_gasto', models.CharField(help_text='Clave o ID', max_length=6)),
                ('cuenta_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.GastosCuenta', to_field='descripcion_cuenta_gasto')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SubCuentas Gastos',
                'unique_together': {('cuenta_gasto', 'descripcion_subcuenta_gasto')},
            },
        ),
    ]
