# Generated by Django 2.2.6 on 2020-03-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastossubcuenta',
            name='descripcion_subcuenta_gasto',
            field=models.CharField(help_text='Descripción SubCuenta', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gastossubcuenta',
            name='id_subcuenta_gasto',
            field=models.CharField(help_text='Clave o ID', max_length=6, unique=True),
        ),
    ]
