# Generated by Django 2.2.6 on 2020-03-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_auto_20200302_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastossubcuenta',
            old_name='cuenta_gasto',
            new_name='cuenta',
        ),
        migrations.AlterUniqueTogether(
            name='gastossubcuenta',
            unique_together={('cuenta', 'descripcion_subcuenta_gasto')},
        ),
    ]
