# Generated by Django 2.2.6 on 2020-03-03 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gastos', '0003_auto_20200302_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('id_area', models.CharField(max_length=4, unique=True)),
                ('descripcion_area', models.CharField(max_length=20, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Areas Gasto',
            },
        ),
        migrations.AlterField(
            model_name='gastossubcuenta',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gastos.GastosCuenta', to_field='descripcion_cuenta_gasto'),
        ),
        migrations.CreateModel(
            name='UnidNegocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('id_unidad_negocio', models.CharField(max_length=4, unique=True)),
                ('descripcion_unidad_negocio', models.CharField(max_length=20, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Unidades de Noegocio',
            },
        ),
        migrations.CreateModel(
            name='GastoEnc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.AreaGasto', to_field='descripcion_area')),
                ('unidad_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.UnidNegocio', to_field='descripcion_unidad_negocio')),
            ],
            options={
                'verbose_name': 'Encabezado Gastos',
                'verbose_name_plural': 'Encabezados Gastos',
            },
        ),
        migrations.CreateModel(
            name='GastoDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('PRESUPUESTO', 'PRESUPUESTO'), ('OBJETIVO', 'OBJETIVO'), ('REAL', 'REAL')], max_length=30)),
                ('cantidad', models.FloatField(default=0.0)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gastos.GastoEnc')),
            ],
            options={
                'verbose_name': 'Detalle Gastos',
                'verbose_name_plural': 'Detalles Gastos',
            },
        ),
    ]
