# Generated by Django 2.2.6 on 2020-03-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_auto_20200303_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastodet',
            name='subcuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gastos.GastosSubCuenta'),
            preserve_default=False,
        ),
    ]
